protected settings changes
Azure/custom-script-extension-linux pull request #195
Opened 2022-03-21 18:50 UTC by norakoiralamsft

-- clears out file in config folder (ex: 0.settings)

2022-06-13 20:01 UTC, jscalev requested changes

2022-06-13 20:01 UTC, jscalev commented on main/handlersettings_test.go
> +func createTestFiles(folderPath, settingsExtensionName string) error {
should add a test where we have one of the files open so we can't modify it (extension platform should have a similar test whose logic can be copied)

2022-09-01 20:32 UTC, D1v38om83r commented on main/handlersettings_test.go
> +	defer os.RemoveAll(testFolderPath)
Can call lines with differ right after the Create TestFiles is called.

2022-09-01 20:35 UTC, D1v38om83r commented on main/handlersettingscommon.go
> +func cleanUpSettings(ctx *log.Context, configFolder string) {
Would Azure-Extension-Platform be a better place to define this function in?

2022-09-15 19:49 UTC, norakoiralamsft commented
new PR: https://github.com/Azure/custom-script-extension-linux/pull/201

2022-09-15 19:49 UTC, closed without merging